[package]
name = "artivus-rust-modules"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "AudioBuffer",
  "AudioContext",
] }

# For audio analysis
rustfft = "6.1"
realfft = "3.2" 

[dev-dependencies]
wasm-bindgen-test = "0.3"